import { Link, createFileRoute } from "@tanstack/react-router";

import { LegalDocPage, legalHead, type LegalSection } from "@/components/LegalDocPage";

export const Route = createFileRoute("/legal/privacy")({
  head: legalHead(
    "privacy",
    "ProvisionLoop Privacy Policy v1.0: the exact data categories the app uses, why, who processes it, retention, security and your Texas privacy rights including appeal.",
  ),
  component: PrivacyPage,
});

const SECTIONS: LegalSection[] = [
  {
    id: "scope",
    heading: "Scope",
    body: (
      <p>
        This policy covers personal data ProvisionLoop processes through the ProvisionLoop web
        application and its backend during the Texas pilot. It is written to meet the notice
        requirements of the Texas Data Privacy and Security Act (Texas Business &amp; Commerce Code
        Chapter 541).
      </p>
    ),
  },
  {
    id: "categories",
    heading: "Data categories we actually process",
    body: (
      <>
        <p>These are the categories the application actually uses today — no placeholders.</p>
        <ul>
          <li>
            <strong>Account and contact data.</strong> Email address, password credential held by our
            authentication provider (never in plain text and never visible to us), display name, and
            the role or roles you chose.
          </li>
          <li>
            <strong>Household assistance data.</strong> First name, optional email and phone, service
            area, household size, need type, urgency and free-text notes. Free-text notes can contain{" "}
            <strong>sensitive details</strong> — health, disability, immigration, family or religious
            information — because people describe their situation in their own words.
          </li>
          <li>
            <strong>Kitchen and business data.</strong> Business name, kind, address, service area,
            website, program summary, posted capacity, posted cost per meal, menu templates, claim
            status and payout onboarding status.
          </li>
          <li>
            <strong>Partner and referral data.</strong> Organization name, kind, website, service
            areas, approval status, and the referrals routed to that organization with their status,
            scheduling and outcome.
          </li>
          <li>
            <strong>Volunteer and dispatch data.</strong> Volunteer name, contact, skills,
            availability, shift signups, delivery runs claimed, run status and hours logged.
          </li>
          <li>
            <strong>Transaction identifiers.</strong> Payment session and customer identifiers,
            subscription identifiers, amounts in cents, meal counts, neighborhood, payment
            environment and payout/transfer identifiers.{" "}
            <strong>
              We never receive or store your card number, CVC or bank account number
            </strong>{" "}
            — those go directly to Stripe.
          </li>
          <li>
            <strong>Device and security logs.</strong> Standard server and authentication logs
            generated by our hosting and authentication providers for security, abuse prevention and
            debugging.
          </li>
          <li>
            <strong>Household planning data (MealForge).</strong> Household size, budget,
            preferences, pantry contents, saved recipes and meal plans, stored locally in your
            browser and synced to your account when you are signed in.
          </li>
          <li>
            <strong>Public aggregate ledger.</strong> Meal counts, neighborhood, kitchen name and
            timestamps for completed orders. Recipient identity is never part of it.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "purposes",
    heading: "Why we process each category",
    body: (
      <ul>
        <li>
          <strong>Account data</strong> — to authenticate you, apply your role permissions and secure
          the account.
        </li>
        <li>
          <strong>Assistance data</strong> — solely to route a request to an approved partner
          organization and to let that organization record an outcome.
        </li>
        <li>
          <strong>Kitchen data</strong> — to display accurate capacity and cost, to accept and track
          orders, and to send payouts to the operator.
        </li>
        <li>
          <strong>Partner data</strong> — to review applications, gate access to identifiable request
          data, and record fulfillment.
        </li>
        <li>
          <strong>Volunteer data</strong> — to staff shifts and dispatch delivery runs, and to log
          hours.
        </li>
        <li>
          <strong>Transaction identifiers</strong> — to create checkouts, confirm payment through a
          signed webhook, credit the ledger only for paid meals, pay kitchens, and handle refunds and
          disputes.
        </li>
        <li>
          <strong>Security logs</strong> — to detect abuse, debug failures and meet legal
          obligations.
        </li>
        <li>
          <strong>Aggregate ledger</strong> — to publish honest, non-identifying impact figures.
        </li>
      </ul>
    ),
  },
  {
    id: "minimization",
    heading: "Data minimization and sensitive data",
    body: (
      <>
        <p>
          We ask for the least we need to route help. Assistance requests do not require a full legal
          name, a home address, an income figure, an identity document or a benefits number, and you
          should not include one.
        </p>
        <p>
          Because free-text notes can contain sensitive details, they are treated as sensitive:
          restricted to the approved partner handling the request and to our own administrators for
          support, never shown to sponsors, never shown to volunteers, never used to train models,
          and never published in aggregate views.
        </p>
        <p>
          Volunteers see drop points and run instructions, not household addresses or recipient
          identity.
        </p>
      </>
    ),
  },
  {
    id: "recipients",
    heading: "Who receives data",
    body: (
      <>
        <p>We do not sell personal data and we share it only in these ways.</p>
        <ul>
          <li>
            <strong>Stripe</strong> — payment processing, checkout, subscriptions, connected payout
            accounts.
          </li>
          <li>
            <strong>Supabase</strong> — database hosting, authentication and storage of application
            data.
          </li>
          <li>
            <strong>Lovable</strong> — hosting and build infrastructure for the application itself.
          </li>
          <li>
            <strong>Verified partner organizations</strong> — only the specific request routed to
            them, and only while they are approved and active.
          </li>
          <li>
            <strong>Kitchens</strong> — order quantity, timing and their own volunteer roster. Not
            recipient identity.
          </li>
          <li>
            <strong>Legally required disclosures</strong> — where we must respond to valid legal
            process, protect against fraud, or prevent imminent harm.
          </li>
        </ul>
        <p>
          Sponsors, cities and the public receive aggregate figures only. There is no advertising
          network, analytics broker or data broker in this list.
        </p>
      </>
    ),
  },
  {
    id: "public-private",
    heading: "Public fields versus private fields",
    body: (
      <>
        <p>
          <strong>Public:</strong> kitchen name, kind, city, neighborhood, address, website, program
          summary, posted capacity, posted cost per meal, verification state, and aggregate ledger
          totals by neighborhood and time.
        </p>
        <p>
          <strong>Private, never public:</strong> every assistance request and its notes, referral
          records and outcomes, volunteer identity and rosters, household planning data, transaction
          identifiers, payout details, privacy and refund requests, and legal acceptance records.
          These are protected by row-level security so an account can read only its own rows or rows
          its approved role grants.
        </p>
      </>
    ),
  },
  {
    id: "retention",
    heading: "Retention",
    body: (
      <>
        <p>Our retention principle is: keep it while it is doing the job, then remove it.</p>
        <ul>
          <li>
            <strong>Account data</strong> — while the account exists, then deleted on request subject
            to the exceptions below.
          </li>
          <li>
            <strong>Assistance requests and referrals</strong> — while open, plus a limited period
            afterwards so a partner can verify what happened and correct errors. Target: 24 months,
            then deletion or de-identification.
          </li>
          <li>
            <strong>Volunteer records</strong> — while the profile is active, plus a limited period
            for hours verification. Target: 24 months.
          </li>
          <li>
            <strong>Transaction identifiers and payout records</strong> — retained as financial
            records for as long as tax, accounting and dispute-resolution obligations require.
          </li>
          <li>
            <strong>Legal acceptance records</strong> — retained for the life of the account and
            afterwards as evidence that a version was accepted.
          </li>
          <li>
            <strong>Security logs</strong> — short-lived, retained by our providers under their
            standard log retention.
          </li>
          <li>
            <strong>Aggregate ledger entries</strong> — retained indefinitely; they contain no
            personal identifier.
          </li>
        </ul>
        <p>
          Backups expire on their own schedule; deleted records disappear from backups when those
          backups roll off.
        </p>
      </>
    ),
  },
  {
    id: "security",
    heading: "Security",
    body: (
      <p>
        Data is encrypted in transit. Access is controlled per row by database row-level security
        policies tied to your account and role, privileged operations run only on the server, secrets
        are never shipped to the browser, and payment credentials never touch our systems. No system
        is perfectly secure; we will notify affected people without undue delay if a breach affecting
        their personal data occurs.
      </p>
    ),
  },
  {
    id: "no-sale",
    heading: "No sale, no targeted advertising, no profiling",
    body: (
      <p className="legal-callout">
        ProvisionLoop does not sell personal data, does not process personal data for targeted
        advertising, and does not carry out profiling that produces legal or similarly significant
        effects about you. There is nothing here you need to opt out of for those purposes — but the
        opt-out right below is available anyway.
      </p>
    ),
  },
  {
    id: "rights",
    heading: "Your Texas privacy rights",
    body: (
      <>
        <p>As a Texas resident you can ask us to:</p>
        <ul>
          <li>
            <strong>Confirm and access</strong> the personal data we process about you.
          </li>
          <li>
            <strong>Correct</strong> inaccuracies.
          </li>
          <li>
            <strong>Delete</strong> personal data we hold about you.
          </li>
          <li>
            <strong>Port</strong> a copy in a portable, readily usable format where processing is
            automated.
          </li>
          <li>
            <strong>Opt out</strong> of sale, targeted advertising or significant profiling (we do
            none of these).
          </li>
        </ul>
        <p>
          Submit any of these through the <Link to="/privacy-center">Privacy Center</Link> while
          signed in. We aim to respond within 45 days and may extend once by a further 45 days where
          reasonably necessary, telling you why.
        </p>
        <p>
          <strong>Appeal.</strong> If we refuse a request, you may appeal it in the Privacy Center by
          choosing &ldquo;Appeal&rdquo;. We will respond in writing within 60 days with our decision
          and reasons. If the appeal is denied you may complain to the Texas Attorney General.
        </p>
        <p className="legal-callout">
          Pilot limitation: privacy requests are queued for review by a person. There is no automated
          fulfillment pipeline and no admin request queue yet — building one is a launch blocker, and
          we will not pretend a request completed itself.
        </p>
      </>
    ),
  },
  {
    id: "exceptions",
    heading: "Deletion exceptions",
    body: (
      <p>
        We may keep specific records after a deletion request where the law allows or requires it:
        financial and payout records needed for tax, accounting or dispute resolution; legal
        acceptance records that evidence a version you accepted; records needed to investigate fraud
        or protect someone&apos;s safety; and aggregate or de-identified figures that cannot be
        linked back to you. We will tell you which exception applies.
      </p>
    ),
  },
  {
    id: "children",
    heading: "Children",
    body: (
      <p>
        ProvisionLoop accounts are for adults 18 and over. We do not knowingly collect personal data
        from children. If we learn a child created an account, we will delete it. A household adult
        may describe household size, but should not include a child&apos;s identifying details in a
        request.
      </p>
    ),
  },
  {
    id: "cross-border",
    heading: "Where processing happens",
    body: (
      <p>
        The pilot is operated for Texas. Our hosting, database, authentication and payment providers
        operate global infrastructure, so data may be processed or backed up outside Texas and
        potentially outside the United States, under those providers&apos; contractual and technical
        safeguards.
      </p>
    ),
  },
  {
    id: "changes",
    heading: "Changes to this policy",
    body: (
      <p>
        Material changes get a new version number and a new effective date in the{" "}
        <Link to="/legal">Legal Center</Link>. Where a change materially affects your rights we will
        ask you to acknowledge the new version before you continue with the affected action.
      </p>
    ),
  },
  {
    id: "contact",
    heading: "Contacting us",
    body: (
      <p className="legal-callout">
        Signed-in users should use the <Link to="/privacy-center">Privacy Center</Link>; it is the
        only channel we currently monitor. A named operating legal entity and a monitored legal
        contact channel will be published here before the public pilot opens and before any
        live-money launch. We will not publish an invented address or email address in the meantime.
      </p>
    ),
  },
];

function PrivacyPage() {
  return (
    <LegalDocPage
      docKey="privacy"
      intro={
        <p className="text-sm">
          The short version: assistance requests are private and stay private, sponsors and the
          public only ever see aggregates, we never touch your card number, we do not sell data or
          run targeted advertising, and you can access, correct, delete, port, opt out or appeal from
          the Privacy Center.
        </p>
      }
      sections={SECTIONS}
    />
  );
}
