/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as CivicRouteImport } from './routes/civic'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AppShopRouteImport } from './routes/app.shop'
import { Route as AppSetupRouteImport } from './routes/app.setup'
import { Route as AppPlanRouteImport } from './routes/app.plan'
import { Route as AppPantryRouteImport } from './routes/app.pantry'
import { Route as AppKitchenRouteImport } from './routes/app.kitchen'
import { Route as AppImportRouteImport } from './routes/app.import'
import { Route as AppCookRouteImport } from './routes/app.cook'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const CivicRoute = CivicRouteImport.update({
  id: '/civic',
  path: '/civic',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppPantryRoute = AppPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AppRoute,
} as any)
const AppKitchenRoute = AppKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppCookRoute = AppCookRouteImport.update({
  id: '/cook',
  path: '/cook',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/civic': typeof CivicRoute
  '/impact': typeof ImpactRoute
  '/kitchen': typeof KitchenRoute
  '/partners': typeof PartnersRoute
  '/volunteer': typeof VolunteerRoute
  '/app/cook': typeof AppCookRoute
  '/app/import': typeof AppImportRoute
  '/app/kitchen': typeof AppKitchenRoute
  '/app/pantry': typeof AppPantryRoute
  '/app/plan': typeof AppPlanRoute
  '/app/setup': typeof AppSetupRoute
  '/app/shop': typeof AppShopRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/app/': typeof AppIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/civic': typeof CivicRoute
  '/impact': typeof ImpactRoute
  '/kitchen': typeof KitchenRoute
  '/partners': typeof PartnersRoute
  '/volunteer': typeof VolunteerRoute
  '/app/cook': typeof AppCookRoute
  '/app/import': typeof AppImportRoute
  '/app/kitchen': typeof AppKitchenRoute
  '/app/pantry': typeof AppPantryRoute
  '/app/plan': typeof AppPlanRoute
  '/app/setup': typeof AppSetupRoute
  '/app/shop': typeof AppShopRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/app': typeof AppIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/civic': typeof CivicRoute
  '/impact': typeof ImpactRoute
  '/kitchen': typeof KitchenRoute
  '/partners': typeof PartnersRoute
  '/volunteer': typeof VolunteerRoute
  '/app/cook': typeof AppCookRoute
  '/app/import': typeof AppImportRoute
  '/app/kitchen': typeof AppKitchenRoute
  '/app/pantry': typeof AppPantryRoute
  '/app/plan': typeof AppPlanRoute
  '/app/setup': typeof AppSetupRoute
  '/app/shop': typeof AppShopRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/app/': typeof AppIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/civic'
    | '/impact'
    | '/kitchen'
    | '/partners'
    | '/volunteer'
    | '/app/cook'
    | '/app/import'
    | '/app/kitchen'
    | '/app/pantry'
    | '/app/plan'
    | '/app/setup'
    | '/app/shop'
    | '/checkout/return'
    | '/app/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/civic'
    | '/impact'
    | '/kitchen'
    | '/partners'
    | '/volunteer'
    | '/app/cook'
    | '/app/import'
    | '/app/kitchen'
    | '/app/pantry'
    | '/app/plan'
    | '/app/setup'
    | '/app/shop'
    | '/checkout/return'
    | '/app'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/civic'
    | '/impact'
    | '/kitchen'
    | '/partners'
    | '/volunteer'
    | '/app/cook'
    | '/app/import'
    | '/app/kitchen'
    | '/app/pantry'
    | '/app/plan'
    | '/app/setup'
    | '/app/shop'
    | '/checkout/return'
    | '/app/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  CivicRoute: typeof CivicRoute
  ImpactRoute: typeof ImpactRoute
  KitchenRoute: typeof KitchenRoute
  PartnersRoute: typeof PartnersRoute
  VolunteerRoute: typeof VolunteerRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/civic': {
      id: '/civic'
      path: '/civic'
      fullPath: '/civic'
      preLoaderRoute: typeof CivicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/shop': {
      id: '/app/shop'
      path: '/shop'
      fullPath: '/app/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/setup': {
      id: '/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pantry': {
      id: '/app/pantry'
      path: '/pantry'
      fullPath: '/app/pantry'
      preLoaderRoute: typeof AppPantryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kitchen': {
      id: '/app/kitchen'
      path: '/kitchen'
      fullPath: '/app/kitchen'
      preLoaderRoute: typeof AppKitchenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/import': {
      id: '/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cook': {
      id: '/app/cook'
      path: '/cook'
      fullPath: '/app/cook'
      preLoaderRoute: typeof AppCookRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCookRoute: typeof AppCookRoute
  AppImportRoute: typeof AppImportRoute
  AppKitchenRoute: typeof AppKitchenRoute
  AppPantryRoute: typeof AppPantryRoute
  AppPlanRoute: typeof AppPlanRoute
  AppSetupRoute: typeof AppSetupRoute
  AppShopRoute: typeof AppShopRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCookRoute: AppCookRoute,
  AppImportRoute: AppImportRoute,
  AppKitchenRoute: AppKitchenRoute,
  AppPantryRoute: AppPantryRoute,
  AppPlanRoute: AppPlanRoute,
  AppSetupRoute: AppSetupRoute,
  AppShopRoute: AppShopRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  CivicRoute: CivicRoute,
  ImpactRoute: ImpactRoute,
  KitchenRoute: KitchenRoute,
  PartnersRoute: PartnersRoute,
  VolunteerRoute: VolunteerRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
