/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppShopRouteImport } from './routes/app.shop'
import { Route as AppSetupRouteImport } from './routes/app.setup'
import { Route as AppPlanRouteImport } from './routes/app.plan'
import { Route as AppPantryRouteImport } from './routes/app.pantry'
import { Route as AppKitchenRouteImport } from './routes/app.kitchen'
import { Route as AppImportRouteImport } from './routes/app.import'
import { Route as AppCookRouteImport } from './routes/app.cook'

const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppPantryRoute = AppPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AppRoute,
} as any)
const AppKitchenRoute = AppKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppCookRoute = AppCookRouteImport.update({
  id: '/cook',
  path: '/cook',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/impact': typeof ImpactRoute
  '/kitchen': typeof KitchenRoute
  '/app/cook': typeof AppCookRoute
  '/app/import': typeof AppImportRoute
  '/app/kitchen': typeof AppKitchenRoute
  '/app/pantry': typeof AppPantryRoute
  '/app/plan': typeof AppPlanRoute
  '/app/setup': typeof AppSetupRoute
  '/app/shop': typeof AppShopRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/impact': typeof ImpactRoute
  '/kitchen': typeof KitchenRoute
  '/app/cook': typeof AppCookRoute
  '/app/import': typeof AppImportRoute
  '/app/kitchen': typeof AppKitchenRoute
  '/app/pantry': typeof AppPantryRoute
  '/app/plan': typeof AppPlanRoute
  '/app/setup': typeof AppSetupRoute
  '/app/shop': typeof AppShopRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/impact': typeof ImpactRoute
  '/kitchen': typeof KitchenRoute
  '/app/cook': typeof AppCookRoute
  '/app/import': typeof AppImportRoute
  '/app/kitchen': typeof AppKitchenRoute
  '/app/pantry': typeof AppPantryRoute
  '/app/plan': typeof AppPlanRoute
  '/app/setup': typeof AppSetupRoute
  '/app/shop': typeof AppShopRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/impact'
    | '/kitchen'
    | '/app/cook'
    | '/app/import'
    | '/app/kitchen'
    | '/app/pantry'
    | '/app/plan'
    | '/app/setup'
    | '/app/shop'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/impact'
    | '/kitchen'
    | '/app/cook'
    | '/app/import'
    | '/app/kitchen'
    | '/app/pantry'
    | '/app/plan'
    | '/app/setup'
    | '/app/shop'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/impact'
    | '/kitchen'
    | '/app/cook'
    | '/app/import'
    | '/app/kitchen'
    | '/app/pantry'
    | '/app/plan'
    | '/app/setup'
    | '/app/shop'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ImpactRoute: typeof ImpactRoute
  KitchenRoute: typeof KitchenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shop': {
      id: '/app/shop'
      path: '/shop'
      fullPath: '/app/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/setup': {
      id: '/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pantry': {
      id: '/app/pantry'
      path: '/pantry'
      fullPath: '/app/pantry'
      preLoaderRoute: typeof AppPantryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kitchen': {
      id: '/app/kitchen'
      path: '/kitchen'
      fullPath: '/app/kitchen'
      preLoaderRoute: typeof AppKitchenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/import': {
      id: '/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cook': {
      id: '/app/cook'
      path: '/cook'
      fullPath: '/app/cook'
      preLoaderRoute: typeof AppCookRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCookRoute: typeof AppCookRoute
  AppImportRoute: typeof AppImportRoute
  AppKitchenRoute: typeof AppKitchenRoute
  AppPantryRoute: typeof AppPantryRoute
  AppPlanRoute: typeof AppPlanRoute
  AppSetupRoute: typeof AppSetupRoute
  AppShopRoute: typeof AppShopRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCookRoute: AppCookRoute,
  AppImportRoute: AppImportRoute,
  AppKitchenRoute: AppKitchenRoute,
  AppPantryRoute: AppPantryRoute,
  AppPlanRoute: AppPlanRoute,
  AppSetupRoute: AppSetupRoute,
  AppShopRoute: AppShopRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ImpactRoute: ImpactRoute,
  KitchenRoute: KitchenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
