import type { Ingredient } from "./types";

/**
 * Ingredient knowledge graph.
 *
 * Canonical entities with aliases, unit-conversion density, purchasable
 * package sizes, nutrition, storage type, allergens and substitutions.
 * Shared by household planning and community/kitchen batch costing.
 *
 * Prices here are ESTIMATED national baselines. They are never surfaced as
 * live pricing — see `pricing.ts` for provenance handling.
 */
export const INGREDIENTS: Ingredient[] = [
  // ---------- protein ----------
  {
    id: "chicken_thigh",
    name: "Chicken thighs",
    category: "protein",
    storage: "fridge",
    aliases: ["boneless skinless chicken thighs", "chicken thigh", "thighs"],
    packages: [
      { size: 2.5, unit: "lb", label: "2.5 lb family pack", baselinePrice: 8.72 },
      { size: 1, unit: "lb", label: "1 lb", baselinePrice: 3.99 },
    ],
    nutrition: { kcal: 177, protein: 24.8, carbs: 0, fat: 8.2 },
    allergens: [],
    diet: ["meat", "poultry"],
    substitutes: ["chicken_breast"],
    aisle: "Meat & Seafood",
  },
  {
    id: "chicken_breast",
    name: "Chicken breast",
    category: "protein",
    storage: "fridge",
    aliases: ["boneless skinless chicken breast", "chicken breasts"],
    packages: [
      { size: 3, unit: "lb", label: "3 lb value pack", baselinePrice: 11.97 },
      { size: 1, unit: "lb", label: "1 lb", baselinePrice: 4.49 },
    ],
    nutrition: { kcal: 165, protein: 31, carbs: 0, fat: 3.6 },
    allergens: [],
    diet: ["meat", "poultry"],
    substitutes: ["chicken_thigh", "tofu"],
    aisle: "Meat & Seafood",
  },
  {
    id: "ground_beef",
    name: "Ground beef (80/20)",
    category: "protein",
    storage: "fridge",
    aliases: ["ground beef", "hamburger meat", "mince"],
    packages: [
      { size: 1, unit: "lb", label: "1 lb", baselinePrice: 5.29 },
      { size: 3, unit: "lb", label: "3 lb roll", baselinePrice: 14.49 },
    ],
    nutrition: { kcal: 254, protein: 17.2, carbs: 0, fat: 20 },
    allergens: [],
    diet: ["meat", "beef"],
    substitutes: ["ground_turkey", "lentils"],
    aisle: "Meat & Seafood",
  },
  {
    id: "ground_turkey",
    name: "Ground turkey",
    category: "protein",
    storage: "fridge",
    aliases: ["turkey mince"],
    packages: [{ size: 1, unit: "lb", label: "1 lb", baselinePrice: 4.79 }],
    nutrition: { kcal: 203, protein: 27, carbs: 0, fat: 10 },
    allergens: [],
    diet: ["meat", "poultry"],
    substitutes: ["ground_beef"],
    aisle: "Meat & Seafood",
  },
  {
    id: "pork_shoulder",
    name: "Pork shoulder",
    category: "protein",
    storage: "fridge",
    aliases: ["pork butt", "boston butt"],
    packages: [{ size: 4, unit: "lb", label: "4 lb roast", baselinePrice: 9.96 }],
    nutrition: { kcal: 242, protein: 21, carbs: 0, fat: 17 },
    allergens: [],
    diet: ["meat", "pork"],
    aisle: "Meat & Seafood",
  },
  {
    id: "salmon",
    name: "Salmon fillet",
    category: "protein",
    storage: "fridge",
    aliases: ["salmon fillets", "atlantic salmon"],
    packages: [{ size: 1, unit: "lb", label: "1 lb", baselinePrice: 11.99 }],
    nutrition: { kcal: 208, protein: 20, carbs: 0, fat: 13 },
    allergens: ["fish"],
    diet: ["fish"],
    aisle: "Meat & Seafood",
  },
  {
    id: "eggs",
    name: "Eggs",
    category: "dairy",
    storage: "fridge",
    aliases: ["large eggs", "egg"],
    gramsEach: 50,
    packages: [
      { size: 12, unit: "each", label: "dozen", baselinePrice: 3.42 },
      { size: 18, unit: "each", label: "18 ct", baselinePrice: 4.68 },
    ],
    nutrition: { kcal: 143, protein: 12.6, carbs: 0.7, fat: 9.5 },
    allergens: ["egg"],
    diet: ["egg"],
    aisle: "Dairy & Eggs",
  },
  {
    id: "tofu",
    name: "Extra-firm tofu",
    category: "protein",
    storage: "fridge",
    aliases: ["tofu", "firm tofu", "bean curd"],
    packages: [{ size: 14, unit: "oz", label: "14 oz block", baselinePrice: 2.49 }],
    nutrition: { kcal: 144, protein: 17, carbs: 2.8, fat: 8.7 },
    allergens: ["soy"],
    diet: [],
    substitutes: ["chicken_breast"],
    aisle: "Produce",
  },
  {
    id: "black_beans",
    name: "Black beans",
    category: "pantry",
    storage: "pantry",
    aliases: ["canned black beans", "black bean"],
    gramsPerCup: 172,
    packages: [{ size: 15, unit: "oz", label: "15 oz can", baselinePrice: 1.08 }],
    nutrition: { kcal: 132, protein: 8.9, carbs: 23.7, fat: 0.5 },
    allergens: [],
    diet: [],
    substitutes: ["pinto_beans", "lentils"],
    aisle: "Canned & Dry Goods",
  },
  {
    id: "pinto_beans",
    name: "Pinto beans",
    category: "pantry",
    storage: "pantry",
    aliases: ["canned pinto beans"],
    gramsPerCup: 171,
    packages: [{ size: 15, unit: "oz", label: "15 oz can", baselinePrice: 1.04 }],
    nutrition: { kcal: 143, protein: 9, carbs: 26, fat: 0.7 },
    allergens: [],
    diet: [],
    substitutes: ["black_beans"],
    aisle: "Canned & Dry Goods",
  },
  {
    id: "chickpeas",
    name: "Chickpeas",
    category: "pantry",
    storage: "pantry",
    aliases: ["garbanzo beans", "canned chickpeas"],
    gramsPerCup: 164,
    packages: [{ size: 15, unit: "oz", label: "15 oz can", baselinePrice: 1.12 }],
    nutrition: { kcal: 164, protein: 8.9, carbs: 27.4, fat: 2.6 },
    allergens: [],
    diet: [],
    aisle: "Canned & Dry Goods",
  },
  {
    id: "lentils",
    name: "Dry lentils",
    category: "pantry",
    storage: "pantry",
    aliases: ["brown lentils", "red lentils", "lentil"],
    gramsPerCup: 192,
    packages: [{ size: 16, unit: "oz", label: "1 lb bag", baselinePrice: 1.98 }],
    nutrition: { kcal: 353, protein: 25, carbs: 60, fat: 1.1 },
    allergens: [],
    diet: [],
    aisle: "Canned & Dry Goods",
  },

  // ---------- grain ----------
  {
    id: "rice",
    name: "Long-grain white rice",
    category: "grain",
    storage: "pantry",
    aliases: ["white rice", "jasmine rice", "rice"],
    gramsPerCup: 185,
    packages: [
      { size: 5, unit: "lb", label: "5 lb bag", baselinePrice: 5.48 },
      { size: 2, unit: "lb", label: "2 lb bag", baselinePrice: 2.68 },
    ],
    nutrition: { kcal: 365, protein: 7.1, carbs: 80, fat: 0.7 },
    allergens: [],
    diet: [],
    aisle: "Canned & Dry Goods",
  },
  {
    id: "pasta",
    name: "Pasta",
    category: "grain",
    storage: "pantry",
    aliases: ["spaghetti", "penne", "rotini", "noodles"],
    packages: [{ size: 16, unit: "oz", label: "1 lb box", baselinePrice: 1.24 }],
    nutrition: { kcal: 371, protein: 13, carbs: 75, fat: 1.5 },
    allergens: ["wheat"],
    diet: ["gluten"],
    aisle: "Canned & Dry Goods",
  },
  {
    id: "tortillas",
    name: "Flour tortillas",
    category: "bakery",
    storage: "pantry",
    aliases: ["tortilla", "soft tortillas"],
    gramsEach: 45,
    packages: [{ size: 10, unit: "each", label: "10 ct pack", baselinePrice: 2.38 }],
    nutrition: { kcal: 310, protein: 8, carbs: 51, fat: 7 },
    allergens: ["wheat"],
    diet: ["gluten"],
    substitutes: ["corn_tortillas"],
    aisle: "Bakery",
  },
  {
    id: "corn_tortillas",
    name: "Corn tortillas",
    category: "bakery",
    storage: "pantry",
    aliases: ["corn tortilla"],
    gramsEach: 26,
    packages: [{ size: 30, unit: "each", label: "30 ct pack", baselinePrice: 2.18 }],
    nutrition: { kcal: 218, protein: 5.7, carbs: 44.6, fat: 2.9 },
    allergens: [],
    diet: [],
    aisle: "Bakery",
  },
  {
    id: "bread",
    name: "Sandwich bread",
    category: "bakery",
    storage: "pantry",
    aliases: ["loaf of bread", "white bread", "wheat bread"],
    gramsEach: 28,
    packages: [{ size: 20, unit: "slice", label: "20 slice loaf", baselinePrice: 2.64 }],
    nutrition: { kcal: 265, protein: 9, carbs: 49, fat: 3.2 },
    allergens: ["wheat"],
    diet: ["gluten"],
    aisle: "Bakery",
  },
  {
    id: "oats",
    name: "Rolled oats",
    category: "grain",
    storage: "pantry",
    aliases: ["old fashioned oats", "oatmeal"],
    gramsPerCup: 90,
    packages: [{ size: 42, unit: "oz", label: "42 oz canister", baselinePrice: 4.28 }],
    nutrition: { kcal: 379, protein: 13.2, carbs: 67.7, fat: 6.5 },
    allergens: [],
    diet: [],
    aisle: "Breakfast",
  },

  // ---------- produce ----------
  {
    id: "onion",
    name: "Yellow onion",
    category: "produce",
    storage: "pantry",
    aliases: ["onion", "onions", "yellow onions"],
    gramsEach: 150,
    gramsPerCup: 160,
    packages: [
      { size: 3, unit: "lb", label: "3 lb bag", baselinePrice: 3.48 },
      { size: 1, unit: "each", label: "single", baselinePrice: 0.89 },
    ],
    nutrition: { kcal: 40, protein: 1.1, carbs: 9.3, fat: 0.1 },
    allergens: [],
    diet: [],
    aisle: "Produce",
  },
  {
    id: "garlic",
    name: "Garlic",
    category: "produce",
    storage: "pantry",
    aliases: ["garlic clove", "garlic cloves", "fresh garlic"],
    gramsEach: 3,
    packages: [{ size: 3, unit: "each", label: "3 heads", baselinePrice: 1.68 }],
    nutrition: { kcal: 149, protein: 6.4, carbs: 33, fat: 0.5 },
    allergens: [],
    diet: [],
    aisle: "Produce",
  },
  {
    id: "carrot",
    name: "Carrots",
    category: "produce",
    storage: "fridge",
    aliases: ["carrot", "baby carrots"],
    gramsEach: 61,
    gramsPerCup: 128,
    packages: [{ size: 2, unit: "lb", label: "2 lb bag", baselinePrice: 2.18 }],
    nutrition: { kcal: 41, protein: 0.9, carbs: 9.6, fat: 0.2 },
    allergens: [],
    diet: [],
    aisle: "Produce",
  },
  {
    id: "celery",
    name: "Celery",
    category: "produce",
    storage: "fridge",
    aliases: ["celery stalks", "celery stalk"],
    gramsEach: 40,
    gramsPerCup: 101,
    packages: [{ size: 1, unit: "bunch", label: "1 bunch", baselinePrice: 2.28 }],
    nutrition: { kcal: 16, protein: 0.7, carbs: 3, fat: 0.2 },
    allergens: [],
    diet: [],
    aisle: "Produce",
  },
  {
    id: "potato",
    name: "Russet potatoes",
    category: "produce",
    storage: "pantry",
    aliases: ["potato", "potatoes", "russet potato"],
    gramsEach: 173,
    packages: [{ size: 5, unit: "lb", label: "5 lb bag", baselinePrice: 4.48 }],
    nutrition: { kcal: 79, protein: 2.1, carbs: 18, fat: 0.1 },
    allergens: [],
    diet: [],
    aisle: "Produce",
  },
  {
    id: "sweet_potato",
    name: "Sweet potatoes",
    category: "produce",
    storage: "pantry",
    aliases: ["sweet potato", "yam"],
    gramsEach: 130,
    packages: [{ size: 3, unit: "lb", label: "3 lb bag", baselinePrice: 3.87 }],
    nutrition: { kcal: 86, protein: 1.6, carbs: 20, fat: 0.1 },
    allergens: [],
    diet: [],
    aisle: "Produce",
  },
  {
    id: "bell_pepper",
    name: "Bell peppers",
    category: "produce",
    storage: "fridge",
    aliases: ["bell pepper", "red bell pepper", "green pepper"],
    gramsEach: 119,
    gramsPerCup: 149,
    packages: [
      { size: 3, unit: "each", label: "3 ct pack", baselinePrice: 3.98 },
      { size: 1, unit: "each", label: "single", baselinePrice: 1.48 },
    ],
    nutrition: { kcal: 31, protein: 1, carbs: 6, fat: 0.3 },
    allergens: [],
    diet: [],
    aisle: "Produce",
  },
  {
    id: "broccoli",
    name: "Broccoli",
    category: "produce",
    storage: "fridge",
    aliases: ["broccoli crowns", "broccoli florets"],
    gramsPerCup: 91,
    packages: [{ size: 1, unit: "lb", label: "1 lb crowns", baselinePrice: 2.48 }],
    nutrition: { kcal: 34, protein: 2.8, carbs: 6.6, fat: 0.4 },
    allergens: [],
    diet: [],
    aisle: "Produce",
  },
  {
    id: "spinach",
    name: "Baby spinach",
    category: "produce",
    storage: "fridge",
    aliases: ["spinach", "fresh spinach"],
    gramsPerCup: 30,
    packages: [
      { size: 10, unit: "oz", label: "10 oz clamshell", baselinePrice: 3.28 },
      { size: 5, unit: "oz", label: "5 oz clamshell", baselinePrice: 2.28 },
    ],
    nutrition: { kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4 },
    allergens: [],
    diet: [],
    aisle: "Produce",
  },
  {
    id: "tomato",
    name: "Roma tomatoes",
    category: "produce",
    storage: "pantry",
    aliases: ["tomato", "tomatoes", "roma tomato"],
    gramsEach: 62,
    packages: [{ size: 1, unit: "lb", label: "1 lb", baselinePrice: 1.98 }],
    nutrition: { kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2 },
    allergens: [],
    diet: [],
    substitutes: ["canned_tomatoes"],
    aisle: "Produce",
  },
  {
    id: "lime",
    name: "Limes",
    category: "produce",
    storage: "fridge",
    aliases: ["lime", "fresh lime"],
    gramsEach: 67,
    packages: [{ size: 6, unit: "each", label: "6 ct bag", baselinePrice: 2.28 }],
    allergens: [],
    diet: [],
    aisle: "Produce",
  },
  {
    id: "lemon",
    name: "Lemons",
    category: "produce",
    storage: "fridge",
    aliases: ["lemon", "fresh lemon"],
    gramsEach: 84,
    packages: [{ size: 4, unit: "each", label: "4 ct bag", baselinePrice: 2.68 }],
    allergens: [],
    diet: [],
    substitutes: ["lime"],
    aisle: "Produce",
  },
  {
    id: "cilantro",
    name: "Cilantro",
    category: "produce",
    storage: "fridge",
    aliases: ["fresh cilantro", "coriander leaves"],
    packages: [{ size: 1, unit: "bunch", label: "1 bunch", baselinePrice: 0.88 }],
    allergens: [],
    diet: [],
    aisle: "Produce",
  },
  {
    id: "mushroom",
    name: "Cremini mushrooms",
    category: "produce",
    storage: "fridge",
    aliases: ["mushrooms", "baby bella", "button mushrooms"],
    gramsPerCup: 72,
    packages: [{ size: 8, unit: "oz", label: "8 oz package", baselinePrice: 2.48 }],
    nutrition: { kcal: 22, protein: 3.1, carbs: 3.3, fat: 0.1 },
    allergens: [],
    diet: [],
    aisle: "Produce",
  },
  {
    id: "cabbage",
    name: "Green cabbage",
    category: "produce",
    storage: "fridge",
    aliases: ["cabbage", "head of cabbage"],
    gramsEach: 900,
    gramsPerCup: 89,
    packages: [{ size: 1, unit: "each", label: "1 head", baselinePrice: 2.34 }],
    nutrition: { kcal: 25, protein: 1.3, carbs: 5.8, fat: 0.1 },
    allergens: [],
    diet: [],
    aisle: "Produce",
  },
  {
    id: "zucchini",
    name: "Zucchini",
    category: "produce",
    storage: "fridge",
    aliases: ["courgette", "summer squash"],
    gramsEach: 196,
    packages: [{ size: 1, unit: "lb", label: "1 lb", baselinePrice: 1.98 }],
    nutrition: { kcal: 17, protein: 1.2, carbs: 3.1, fat: 0.3 },
    allergens: [],
    diet: [],
    aisle: "Produce",
  },
  {
    id: "scallion",
    name: "Green onions",
    category: "produce",
    storage: "fridge",
    aliases: ["scallions", "spring onion", "green onion"],
    packages: [{ size: 1, unit: "bunch", label: "1 bunch", baselinePrice: 1.08 }],
    allergens: [],
    diet: [],
    aisle: "Produce",
  },

  // ---------- dairy ----------
  {
    id: "milk",
    name: "Whole milk",
    category: "dairy",
    storage: "fridge",
    aliases: ["milk", "2% milk"],
    gramsPerCup: 244,
    packages: [
      { size: 1, unit: "gal", label: "1 gallon", baselinePrice: 4.12 },
      { size: 0.5, unit: "gal", label: "half gallon", baselinePrice: 2.68 },
    ],
    nutrition: { kcal: 61, protein: 3.2, carbs: 4.8, fat: 3.3 },
    allergens: ["milk"],
    diet: ["dairy"],
    aisle: "Dairy & Eggs",
  },
  {
    id: "butter",
    name: "Butter",
    category: "dairy",
    storage: "fridge",
    aliases: ["unsalted butter", "salted butter"],
    gramsPerCup: 227,
    packages: [{ size: 16, unit: "oz", label: "1 lb / 4 sticks", baselinePrice: 4.68 }],
    nutrition: { kcal: 717, protein: 0.9, carbs: 0.1, fat: 81 },
    allergens: ["milk"],
    diet: ["dairy"],
    substitutes: ["olive_oil"],
    aisle: "Dairy & Eggs",
  },
  {
    id: "cheddar",
    name: "Shredded cheddar",
    category: "dairy",
    storage: "fridge",
    aliases: ["cheddar cheese", "shredded cheese", "cheese"],
    gramsPerCup: 113,
    packages: [
      { size: 8, unit: "oz", label: "8 oz bag", baselinePrice: 2.98 },
      { size: 16, unit: "oz", label: "16 oz bag", baselinePrice: 4.98 },
    ],
    nutrition: { kcal: 403, protein: 25, carbs: 1.3, fat: 33 },
    allergens: ["milk"],
    diet: ["dairy"],
    aisle: "Dairy & Eggs",
  },
  {
    id: "parmesan",
    name: "Parmesan",
    category: "dairy",
    storage: "fridge",
    aliases: ["parmesan cheese", "grated parmesan"],
    gramsPerCup: 100,
    packages: [{ size: 8, unit: "oz", label: "8 oz wedge", baselinePrice: 5.48 }],
    nutrition: { kcal: 431, protein: 38, carbs: 4.1, fat: 29 },
    allergens: ["milk"],
    diet: ["dairy"],
    aisle: "Dairy & Eggs",
  },
  {
    id: "yogurt",
    name: "Plain Greek yogurt",
    category: "dairy",
    storage: "fridge",
    aliases: ["greek yogurt", "yoghurt"],
    gramsPerCup: 245,
    packages: [{ size: 32, unit: "oz", label: "32 oz tub", baselinePrice: 5.48 }],
    nutrition: { kcal: 59, protein: 10, carbs: 3.6, fat: 0.4 },
    allergens: ["milk"],
    diet: ["dairy"],
    substitutes: ["sour_cream"],
    aisle: "Dairy & Eggs",
  },
  {
    id: "sour_cream",
    name: "Sour cream",
    category: "dairy",
    storage: "fridge",
    aliases: ["sourcream"],
    gramsPerCup: 230,
    packages: [{ size: 16, unit: "oz", label: "16 oz tub", baselinePrice: 2.48 }],
    allergens: ["milk"],
    diet: ["dairy"],
    substitutes: ["yogurt"],
    aisle: "Dairy & Eggs",
  },

  // ---------- pantry ----------
  {
    id: "olive_oil",
    name: "Olive oil",
    category: "pantry",
    storage: "pantry",
    aliases: ["extra virgin olive oil", "evoo", "oil"],
    gramsPerCup: 216,
    packages: [{ size: 25, unit: "floz", label: "25 fl oz bottle", baselinePrice: 8.98 }],
    nutrition: { kcal: 884, protein: 0, carbs: 0, fat: 100 },
    allergens: [],
    diet: [],
    substitutes: ["vegetable_oil"],
    aisle: "Oils & Condiments",
  },
  {
    id: "vegetable_oil",
    name: "Vegetable oil",
    category: "pantry",
    storage: "pantry",
    aliases: ["canola oil", "neutral oil"],
    gramsPerCup: 218,
    packages: [{ size: 48, unit: "floz", label: "48 fl oz bottle", baselinePrice: 4.28 }],
    allergens: [],
    diet: [],
    aisle: "Oils & Condiments",
  },
  {
    id: "canned_tomatoes",
    name: "Crushed tomatoes",
    category: "pantry",
    storage: "pantry",
    aliases: ["canned tomatoes", "diced tomatoes", "tomato sauce"],
    gramsPerCup: 245,
    packages: [
      { size: 28, unit: "oz", label: "28 oz can", baselinePrice: 2.18 },
      { size: 15, unit: "oz", label: "15 oz can", baselinePrice: 1.18 },
    ],
    nutrition: { kcal: 32, protein: 1.6, carbs: 7.3, fat: 0.3 },
    allergens: [],
    diet: [],
    aisle: "Canned & Dry Goods",
  },
  {
    id: "coconut_milk",
    name: "Coconut milk",
    category: "pantry",
    storage: "pantry",
    aliases: ["canned coconut milk"],
    gramsPerCup: 226,
    packages: [{ size: 13.5, unit: "oz", label: "13.5 oz can", baselinePrice: 2.28 }],
    allergens: ["tree_nut"],
    diet: [],
    aisle: "Canned & Dry Goods",
  },
  {
    id: "chicken_broth",
    name: "Chicken broth",
    category: "pantry",
    storage: "pantry",
    aliases: ["chicken stock", "broth", "stock"],
    gramsPerCup: 240,
    packages: [{ size: 32, unit: "floz", label: "32 oz carton", baselinePrice: 2.48 }],
    allergens: [],
    diet: ["meat", "poultry"],
    substitutes: ["veg_broth"],
    aisle: "Canned & Dry Goods",
  },
  {
    id: "veg_broth",
    name: "Vegetable broth",
    category: "pantry",
    storage: "pantry",
    aliases: ["vegetable stock"],
    gramsPerCup: 240,
    packages: [{ size: 32, unit: "floz", label: "32 oz carton", baselinePrice: 2.38 }],
    allergens: [],
    diet: [],
    aisle: "Canned & Dry Goods",
  },
  {
    id: "soy_sauce",
    name: "Soy sauce",
    category: "pantry",
    storage: "pantry",
    aliases: ["shoyu", "light soy sauce"],
    gramsPerCup: 255,
    packages: [{ size: 15, unit: "floz", label: "15 fl oz bottle", baselinePrice: 3.28 }],
    allergens: ["soy", "wheat"],
    diet: ["gluten"],
    aisle: "Oils & Condiments",
  },
  {
    id: "peanut_butter",
    name: "Peanut butter",
    category: "pantry",
    storage: "pantry",
    aliases: ["pb", "creamy peanut butter"],
    gramsPerCup: 258,
    packages: [{ size: 16, unit: "oz", label: "16 oz jar", baselinePrice: 3.18 }],
    nutrition: { kcal: 588, protein: 25, carbs: 20, fat: 50 },
    allergens: ["peanut"],
    diet: [],
    aisle: "Oils & Condiments",
  },
  {
    id: "flour",
    name: "All-purpose flour",
    category: "pantry",
    storage: "pantry",
    aliases: ["ap flour", "plain flour"],
    gramsPerCup: 125,
    packages: [{ size: 5, unit: "lb", label: "5 lb bag", baselinePrice: 3.48 }],
    allergens: ["wheat"],
    diet: ["gluten"],
    aisle: "Baking",
  },
  {
    id: "sugar",
    name: "Granulated sugar",
    category: "pantry",
    storage: "pantry",
    aliases: ["sugar", "white sugar"],
    gramsPerCup: 200,
    packages: [{ size: 4, unit: "lb", label: "4 lb bag", baselinePrice: 3.28 }],
    allergens: [],
    diet: [],
    aisle: "Baking",
  },

  // ---------- spice ----------
  {
    id: "salt",
    name: "Kosher salt",
    category: "spice",
    storage: "pantry",
    aliases: ["salt", "sea salt"],
    gramsPerCup: 230,
    packages: [{ size: 48, unit: "oz", label: "3 lb box", baselinePrice: 4.18 }],
    allergens: [],
    diet: [],
    aisle: "Spices",
  },
  {
    id: "black_pepper",
    name: "Black pepper",
    category: "spice",
    storage: "pantry",
    aliases: ["pepper", "ground black pepper"],
    gramsPerCup: 110,
    packages: [{ size: 3, unit: "oz", label: "3 oz jar", baselinePrice: 3.98 }],
    allergens: [],
    diet: [],
    aisle: "Spices",
  },
  {
    id: "cumin",
    name: "Ground cumin",
    category: "spice",
    storage: "pantry",
    aliases: ["cumin"],
    gramsPerCup: 100,
    packages: [{ size: 2, unit: "oz", label: "2 oz jar", baselinePrice: 2.98 }],
    allergens: [],
    diet: [],
    aisle: "Spices",
  },
  {
    id: "chili_powder",
    name: "Chili powder",
    category: "spice",
    storage: "pantry",
    aliases: ["chilli powder"],
    gramsPerCup: 100,
    packages: [{ size: 2.5, unit: "oz", label: "2.5 oz jar", baselinePrice: 2.68 }],
    allergens: [],
    diet: [],
    aisle: "Spices",
  },
  {
    id: "paprika",
    name: "Smoked paprika",
    category: "spice",
    storage: "pantry",
    aliases: ["paprika"],
    gramsPerCup: 100,
    packages: [{ size: 2, unit: "oz", label: "2 oz jar", baselinePrice: 3.18 }],
    allergens: [],
    diet: [],
    aisle: "Spices",
  },
  {
    id: "oregano",
    name: "Dried oregano",
    category: "spice",
    storage: "pantry",
    aliases: ["oregano"],
    gramsPerCup: 45,
    packages: [{ size: 0.75, unit: "oz", label: "0.75 oz jar", baselinePrice: 2.48 }],
    allergens: [],
    diet: [],
    aisle: "Spices",
  },
  {
    id: "curry_powder",
    name: "Curry powder",
    category: "spice",
    storage: "pantry",
    aliases: ["madras curry powder"],
    gramsPerCup: 100,
    packages: [{ size: 2, unit: "oz", label: "2 oz jar", baselinePrice: 3.48 }],
    allergens: [],
    diet: [],
    aisle: "Spices",
  },
  {
    id: "ginger",
    name: "Fresh ginger",
    category: "produce",
    storage: "fridge",
    aliases: ["ginger root", "ginger"],
    gramsPerCup: 96,
    packages: [{ size: 4, unit: "oz", label: "4 oz knob", baselinePrice: 1.28 }],
    allergens: [],
    diet: [],
    aisle: "Produce",
  },

  // ---------- frozen ----------
  {
    id: "frozen_peas",
    name: "Frozen peas",
    category: "frozen",
    storage: "freezer",
    aliases: ["peas", "green peas"],
    gramsPerCup: 145,
    packages: [{ size: 16, unit: "oz", label: "16 oz bag", baselinePrice: 1.68 }],
    nutrition: { kcal: 81, protein: 5.4, carbs: 14.5, fat: 0.4 },
    allergens: [],
    diet: [],
    aisle: "Frozen",
  },
  {
    id: "frozen_corn",
    name: "Frozen corn",
    category: "frozen",
    storage: "freezer",
    aliases: ["corn", "sweet corn"],
    gramsPerCup: 165,
    packages: [{ size: 16, unit: "oz", label: "16 oz bag", baselinePrice: 1.58 }],
    allergens: [],
    diet: [],
    aisle: "Frozen",
  },
  {
    id: "frozen_broccoli",
    name: "Frozen broccoli",
    category: "frozen",
    storage: "freezer",
    aliases: ["frozen broccoli florets"],
    gramsPerCup: 156,
    packages: [{ size: 12, unit: "oz", label: "12 oz bag", baselinePrice: 1.48 }],
    allergens: [],
    diet: [],
    substitutes: ["broccoli"],
    aisle: "Frozen",
  },
];

export const INGREDIENT_BY_ID: Record<string, Ingredient> = Object.fromEntries(
  INGREDIENTS.map((i) => [i.id, i]),
);

function normalizeToken(s: string): string {
  return s
    .toLowerCase()
    .replace(/\([^)]*\)/g, " ")
    .replace(/[^a-z\s-]/g, " ")
    .replace(
      /\b(fresh|freshly|chopped|minced|diced|sliced|shredded|grated|ground|large|small|medium|boneless|skinless|organic|low[- ]sodium|reduced[- ]fat|extra[- ]virgin|to taste|optional|drained|rinsed|thinly|roughly|finely|cooked|raw|ripe|frozen|canned|dry|dried)\b/g,
      " ",
    )
    .replace(/\s+/g, " ")
    .trim();
}

const ALIAS_INDEX: Array<{ key: string; id: string }> = (() => {
  const rows: Array<{ key: string; id: string }> = [];
  for (const ing of INGREDIENTS) {
    rows.push({ key: normalizeToken(ing.name), id: ing.id });
    for (const a of ing.aliases) rows.push({ key: normalizeToken(a), id: ing.id });
  }
  // longest keys first so "sweet potato" beats "potato"
  return rows.sort((a, b) => b.key.length - a.key.length);
})();

export interface IngredientMatch {
  ingredientId: string;
  /** 0–1 match confidence, used for extraction confidence scoring */
  confidence: number;
}

/** Resolves free-text like "2 cloves garlic, minced" to a canonical ingredient. */
export function matchIngredient(text: string): IngredientMatch | null {
  const norm = normalizeToken(text);
  if (!norm) return null;

  for (const row of ALIAS_INDEX) {
    if (norm === row.key) return { ingredientId: row.id, confidence: 1 };
  }
  for (const row of ALIAS_INDEX) {
    if (row.key.length >= 4 && norm.includes(row.key)) {
      return { ingredientId: row.id, confidence: 0.8 };
    }
  }
  // last resort: single significant word overlap
  const words = norm.split(" ").filter((w) => w.length > 3);
  for (const row of ALIAS_INDEX) {
    if (words.some((w) => row.key.split(" ").includes(w))) {
      return { ingredientId: row.id, confidence: 0.55 };
    }
  }
  return null;
}
