import type { Recipe, RecipeIngredient } from "./types";

/**
 * Seed recipe library. Every recipe is normalized against the ingredient
 * knowledge graph, and carries a source record with extraction method and
 * confidence — exactly like an imported recipe does.
 */

function ri(
  ingredientId: string,
  amount: number,
  unit: string,
  extra?: Partial<RecipeIngredient>,
): RecipeIngredient {
  return { ingredientId, quantity: { amount, unit }, ...extra };
}

function seed(
  id: string,
  title: string,
  servings: number,
  totalTimeMinutes: number,
  tags: string[],
  equipment: string[],
  ingredients: RecipeIngredient[],
  steps: string[],
): Recipe {
  return {
    id,
    title,
    servings,
    totalTimeMinutes,
    tags,
    equipment,
    ingredients,
    steps,
    source: {
      kind: "manual",
      extractionMethod: "manual",
      confidence: 1,
      importedAt: "2026-01-01T00:00:00.000Z",
    },
  };
}

export const SEED_RECIPES: Recipe[] = [
  seed(
    "sheet_pan_chicken",
    "Sheet-pan chicken thighs with potatoes",
    4,
    45,
    ["dinner", "one-pan", "budget"],
    ["oven", "sheet pan"],
    [
      ri("chicken_thigh", 2, "lb"),
      ri("potato", 1.5, "lb"),
      ri("onion", 1, "each"),
      ri("olive_oil", 2, "tbsp"),
      ri("paprika", 2, "tsp"),
      ri("garlic", 4, "clove"),
      ri("salt", 1, "tsp"),
      ri("black_pepper", 0.5, "tsp"),
    ],
    [
      "Heat the oven to 425°F.",
      "Toss potatoes, onion and garlic with oil, paprika, salt and pepper on a sheet pan.",
      "Nestle the chicken thighs on top, skin side up, and season.",
      "Roast 35–40 minutes until the chicken reaches 175°F and the potatoes are crisp.",
    ],
  ),

  seed(
    "black_bean_tacos",
    "Black bean and sweet potato tacos",
    4,
    30,
    ["dinner", "vegetarian", "fast", "budget"],
    ["skillet"],
    [
      ri("sweet_potato", 1.5, "lb"),
      ri("black_beans", 2, "can"),
      ri("corn_tortillas", 12, "each"),
      ri("cumin", 2, "tsp"),
      ri("chili_powder", 2, "tsp"),
      ri("olive_oil", 2, "tbsp"),
      ri("lime", 2, "each"),
      ri("cilantro", 0.5, "bunch", { optional: true }),
      ri("onion", 1, "each"),
    ],
    [
      "Dice the sweet potato and cook in oil over medium-high until tender, 12 minutes.",
      "Add onion, cumin and chili powder; cook 4 minutes.",
      "Stir in drained beans and warm through.",
      "Warm the tortillas and fill; finish with lime and cilantro.",
    ],
  ),

  seed(
    "red_lentil_curry",
    "Red lentil coconut curry",
    4,
    35,
    ["dinner", "vegan", "budget", "batch"],
    ["pot"],
    [
      ri("lentils", 1.5, "cup"),
      ri("coconut_milk", 1, "can"),
      ri("canned_tomatoes", 1, "can"),
      ri("onion", 1, "each"),
      ri("garlic", 3, "clove"),
      ri("ginger", 1, "tbsp"),
      ri("curry_powder", 2, "tbsp"),
      ri("veg_broth", 3, "cup"),
      ri("rice", 2, "cup"),
      ri("spinach", 4, "oz"),
    ],
    [
      "Sweat onion, garlic and ginger in oil until soft.",
      "Add curry powder and toast 1 minute.",
      "Add lentils, tomatoes, coconut milk and broth; simmer 22 minutes.",
      "Fold in spinach and serve over rice.",
    ],
  ),

  seed(
    "beef_chili",
    "Weeknight beef chili",
    6,
    50,
    ["dinner", "batch", "freezer"],
    ["pot"],
    [
      ri("ground_beef", 1.5, "lb"),
      ri("pinto_beans", 2, "can"),
      ri("canned_tomatoes", 2, "can"),
      ri("onion", 1, "each"),
      ri("bell_pepper", 2, "each"),
      ri("garlic", 4, "clove"),
      ri("chili_powder", 3, "tbsp"),
      ri("cumin", 1, "tbsp"),
      ri("chicken_broth", 2, "cup"),
    ],
    [
      "Brown the beef in a heavy pot; drain excess fat.",
      "Add onion, pepper and garlic; cook 6 minutes.",
      "Stir in spices, tomatoes, beans and broth.",
      "Simmer uncovered 30 minutes, stirring occasionally.",
    ],
  ),

  seed(
    "chicken_fried_rice",
    "Chicken fried rice",
    4,
    25,
    ["dinner", "fast", "leftovers"],
    ["wok", "skillet"],
    [
      ri("chicken_breast", 1, "lb"),
      ri("rice", 3, "cup"),
      ri("eggs", 3, "each"),
      ri("frozen_peas", 1.5, "cup"),
      ri("carrot", 2, "each"),
      ri("scallion", 4, "each"),
      ri("soy_sauce", 3, "tbsp"),
      ri("vegetable_oil", 2, "tbsp"),
      ri("garlic", 3, "clove"),
    ],
    [
      "Cook the rice ahead and chill it — day-old rice fries best.",
      "Sear diced chicken in a hot wok; remove.",
      "Scramble the eggs, add carrot, peas, garlic and rice.",
      "Return the chicken, add soy sauce, toss hard for 3 minutes, finish with scallion.",
    ],
  ),

  seed(
    "pasta_pomodoro",
    "Pasta pomodoro",
    4,
    25,
    ["dinner", "vegetarian", "fast", "budget"],
    ["pot", "skillet"],
    [
      ri("pasta", 1, "lb"),
      ri("canned_tomatoes", 2, "can"),
      ri("garlic", 5, "clove"),
      ri("olive_oil", 3, "tbsp"),
      ri("parmesan", 3, "oz"),
      ri("salt", 1, "tsp"),
    ],
    [
      "Boil the pasta one minute short of the package time; save a cup of water.",
      "Sizzle sliced garlic in olive oil, add tomatoes, simmer 12 minutes.",
      "Toss the pasta in the sauce with the reserved water.",
      "Finish off heat with parmesan.",
    ],
  ),

  seed(
    "turkey_taco_skillet",
    "Ground turkey taco skillet",
    4,
    30,
    ["dinner", "one-pan", "fast"],
    ["skillet"],
    [
      ri("ground_turkey", 1, "lb"),
      ri("rice", 1.5, "cup"),
      ri("black_beans", 1, "can"),
      ri("frozen_corn", 1.5, "cup"),
      ri("canned_tomatoes", 1, "can"),
      ri("chili_powder", 2, "tbsp"),
      ri("cheddar", 4, "oz"),
      ri("chicken_broth", 2, "cup"),
      ri("onion", 1, "each"),
    ],
    [
      "Brown the turkey with the onion.",
      "Add spices, rice, beans, corn, tomatoes and broth.",
      "Cover and simmer 20 minutes until the rice is tender.",
      "Top with cheddar, cover off heat until melted.",
    ],
  ),

  seed(
    "tofu_stirfry",
    "Ginger tofu and broccoli stir-fry",
    4,
    30,
    ["dinner", "vegan", "fast"],
    ["wok", "skillet"],
    [
      ri("tofu", 28, "oz"),
      ri("broccoli", 1.5, "lb"),
      ri("soy_sauce", 4, "tbsp"),
      ri("ginger", 2, "tbsp"),
      ri("garlic", 4, "clove"),
      ri("rice", 2, "cup"),
      ri("vegetable_oil", 2, "tbsp"),
      ri("scallion", 3, "each"),
    ],
    [
      "Press and cube the tofu; sear until golden on most sides.",
      "Add broccoli with a splash of water and cover 3 minutes.",
      "Add garlic and ginger, then soy sauce; toss to glaze.",
      "Serve over rice with scallions.",
    ],
  ),

  seed(
    "salmon_roast",
    "Roast salmon with lemon potatoes",
    4,
    35,
    ["dinner", "pescatarian"],
    ["oven", "sheet pan"],
    [
      ri("salmon", 1.5, "lb"),
      ri("potato", 1.5, "lb"),
      ri("lemon", 2, "each"),
      ri("olive_oil", 3, "tbsp"),
      ri("garlic", 3, "clove"),
      ri("oregano", 1, "tbsp"),
    ],
    [
      "Roast sliced potatoes with oil, garlic and oregano at 425°F for 25 minutes.",
      "Add the salmon and lemon slices to the pan.",
      "Roast 10–12 minutes more until the salmon flakes.",
    ],
  ),

  seed(
    "chickpea_shakshuka",
    "Chickpea shakshuka",
    4,
    30,
    ["dinner", "vegetarian", "budget", "fast"],
    ["skillet"],
    [
      ri("chickpeas", 2, "can"),
      ri("canned_tomatoes", 2, "can"),
      ri("eggs", 6, "each"),
      ri("bell_pepper", 2, "each"),
      ri("onion", 1, "each"),
      ri("cumin", 2, "tsp"),
      ri("paprika", 2, "tsp"),
      ri("bread", 6, "slice"),
      ri("olive_oil", 2, "tbsp"),
    ],
    [
      "Soften onion and pepper in oil, add spices.",
      "Add tomatoes and chickpeas; simmer 12 minutes until thick.",
      "Make wells, crack in the eggs, cover and cook 7 minutes.",
      "Serve with toasted bread.",
    ],
  ),

  seed(
    "pork_carnitas",
    "Slow pork carnitas",
    6,
    200,
    ["dinner", "batch", "weekend"],
    ["oven", "dutch oven"],
    [
      ri("pork_shoulder", 4, "lb"),
      ri("onion", 2, "each"),
      ri("garlic", 6, "clove"),
      ri("cumin", 1, "tbsp"),
      ri("oregano", 1, "tbsp"),
      ri("lime", 3, "each"),
      ri("corn_tortillas", 18, "each"),
      ri("chicken_broth", 2, "cup"),
    ],
    [
      "Season the pork heavily and sear on all sides.",
      "Add aromatics and broth, cover, and braise at 300°F for 3 hours.",
      "Shred, then crisp under the broiler.",
      "Serve in warm tortillas with lime.",
    ],
  ),

  seed(
    "veggie_soup",
    "Pantry vegetable and bean soup",
    6,
    40,
    ["dinner", "vegan", "budget", "batch", "freezer"],
    ["pot"],
    [
      ri("carrot", 3, "each"),
      ri("celery", 4, "each"),
      ri("onion", 1, "each"),
      ri("potato", 1, "lb"),
      ri("cabbage", 0.5, "each"),
      ri("canned_tomatoes", 1, "can"),
      ri("pinto_beans", 2, "can"),
      ri("veg_broth", 8, "cup"),
      ri("olive_oil", 2, "tbsp"),
    ],
    [
      "Sweat the onion, carrot and celery in oil for 8 minutes.",
      "Add potato, cabbage, tomatoes, beans and broth.",
      "Simmer 25 minutes; season aggressively.",
    ],
  ),

  seed(
    "mushroom_pasta",
    "Mushroom and spinach pasta",
    4,
    30,
    ["dinner", "vegetarian", "fast"],
    ["pot", "skillet"],
    [
      ri("pasta", 1, "lb"),
      ri("mushroom", 1, "lb"),
      ri("spinach", 5, "oz"),
      ri("garlic", 4, "clove"),
      ri("butter", 3, "tbsp"),
      ri("parmesan", 3, "oz"),
      ri("olive_oil", 2, "tbsp"),
    ],
    [
      "Boil the pasta; reserve a cup of water.",
      "Brown the mushrooms hard in oil, then add butter and garlic.",
      "Wilt the spinach, add pasta and water, toss with parmesan.",
    ],
  ),

  seed(
    "egg_fried_potatoes",
    "Skillet potatoes, eggs and greens",
    4,
    30,
    ["dinner", "vegetarian", "budget", "fast"],
    ["skillet"],
    [
      ri("potato", 2, "lb"),
      ri("eggs", 8, "each"),
      ri("spinach", 5, "oz"),
      ri("onion", 1, "each"),
      ri("olive_oil", 3, "tbsp"),
      ri("paprika", 2, "tsp"),
      ri("cheddar", 3, "oz", { optional: true }),
    ],
    [
      "Parboil diced potatoes 6 minutes, drain well.",
      "Crisp them in a hot skillet with oil, onion and paprika.",
      "Wilt in the spinach, make wells and fry the eggs on top.",
    ],
  ),

  seed(
    "chicken_rice_soup",
    "Chicken, rice and carrot soup",
    6,
    45,
    ["dinner", "soup", "budget", "batch"],
    ["pot"],
    [
      ri("chicken_thigh", 1.5, "lb"),
      ri("rice", 1, "cup"),
      ri("carrot", 0.75, "lb"),
      ri("celery", 3, "stalk"),
      ri("onion", 1, "each"),
      ri("chicken_broth", 32, "floz"),
      ri("olive_oil", 2, "tbsp"),
      ri("salt", 1.5, "tsp"),
      ri("black_pepper", 0.5, "tsp"),
    ],
    [
      "Sweat onion, carrot and celery in oil until soft.",
      "Add chicken, broth and 4 cups water; simmer 20 minutes.",
      "Shred the chicken, add rice and simmer 15 minutes more; season.",
    ],
  ),

  seed(
    "beans_and_rice",
    "Pinto beans and rice with cumin",
    6,
    35,
    ["dinner", "vegetarian", "budget", "pantry"],
    ["pot", "skillet"],
    [
      ri("pinto_beans", 3, "can"),
      ri("rice", 2, "cup"),
      ri("onion", 1, "each"),
      ri("garlic", 3, "clove"),
      ri("cumin", 2, "tsp"),
      ri("chili_powder", 1, "tsp"),
      ri("vegetable_oil", 2, "tbsp"),
      ri("lime", 1, "each"),
      ri("cilantro", 0.5, "bunch", { optional: true }),
    ],
    [
      "Cook the rice with a pinch of salt.",
      "Fry onion and garlic, add spices, then the beans with their liquid.",
      "Simmer 15 minutes, mash lightly, finish with lime and cilantro.",
    ],
  ),

  seed(
    "baked_ziti",
    "Baked pasta with tomato and cheddar",
    6,
    50,
    ["dinner", "vegetarian", "batch", "oven"],
    ["oven", "pot"],
    [
      ri("pasta", 16, "oz"),
      ri("canned_tomatoes", 28, "oz"),
      ri("onion", 1, "each"),
      ri("garlic", 4, "clove"),
      ri("cheddar", 8, "oz"),
      ri("olive_oil", 2, "tbsp"),
      ri("oregano", 2, "tsp"),
      ri("parmesan", 2, "oz", { optional: true }),
    ],
    [
      "Boil the pasta two minutes short of al dente.",
      "Build a quick sauce with oil, onion, garlic, tomatoes and oregano.",
      "Combine, top with cheese and bake 25 minutes at 400°F.",
    ],
  ),

  seed(
    "peanut_noodles",
    "Peanut noodles with cabbage and carrot",
    4,
    25,
    ["dinner", "vegetarian", "fast", "budget"],
    ["pot", "skillet"],
    [
      ri("pasta", 12, "oz"),
      ri("peanut_butter", 0.5, "cup"),
      ri("soy_sauce", 3, "tbsp"),
      ri("cabbage", 0.5, "each"),
      ri("carrot", 0.5, "lb"),
      ri("garlic", 3, "clove"),
      ri("ginger", 1, "tbsp"),
      ri("scallion", 0.5, "bunch"),
    ],
    [
      "Boil the noodles and reserve a cup of cooking water.",
      "Whisk peanut butter, soy sauce, garlic, ginger and hot water into a sauce.",
      "Toss noodles with shredded cabbage, carrot, sauce and scallions.",
    ],
  ),

  seed(
    "shepherds_pie",
    "Turkey and potato shepherd's pie",
    6,
    60,
    ["dinner", "oven", "batch"],
    ["oven", "skillet", "pot"],
    [
      ri("ground_turkey", 1.5, "lb"),
      ri("potato", 2.5, "lb"),
      ri("frozen_peas", 10, "oz"),
      ri("carrot", 0.5, "lb"),
      ri("onion", 1, "each"),
      ri("butter", 3, "tbsp"),
      ri("milk", 0.5, "cup"),
      ri("chicken_broth", 8, "floz"),
      ri("salt", 1.5, "tsp"),
    ],
    [
      "Boil and mash the potatoes with butter and milk.",
      "Brown the turkey with onion and carrot, add broth and peas, simmer to thicken.",
      "Top with mash and bake 25 minutes at 400°F until browned.",
    ],
  ),

  seed(
    "egg_curry",
    "Egg and chickpea curry",
    4,
    30,
    ["dinner", "vegetarian", "fast", "budget"],
    ["skillet", "pot"],
    [
      ri("eggs", 8, "each"),
      ri("chickpeas", 2, "can"),
      ri("coconut_milk", 13.5, "oz"),
      ri("onion", 1, "each"),
      ri("garlic", 3, "clove"),
      ri("ginger", 1, "tbsp"),
      ri("curry_powder", 1, "tbsp"),
      ri("canned_tomatoes", 15, "oz"),
      ri("rice", 1.5, "cup"),
    ],
    [
      "Hard-boil the eggs and cook the rice.",
      "Fry onion, garlic, ginger and curry powder; add tomatoes and coconut milk.",
      "Add chickpeas, simmer 10 minutes, halve the eggs into the sauce.",
    ],
  ),

  seed(
    "beef_stirfry",
    "Beef and pepper stir-fry",
    4,
    25,
    ["dinner", "fast"],
    ["skillet"],
    [
      ri("ground_beef", 1, "lb"),
      ri("bell_pepper", 2, "each"),
      ri("onion", 1, "each"),
      ri("soy_sauce", 3, "tbsp"),
      ri("garlic", 3, "clove"),
      ri("ginger", 1, "tbsp"),
      ri("rice", 1.5, "cup"),
      ri("vegetable_oil", 2, "tbsp"),
      ri("scallion", 0.5, "bunch"),
    ],
    [
      "Start the rice.",
      "Sear the beef hard in a hot skillet, then add peppers and onion.",
      "Add garlic, ginger and soy sauce, toss one minute, finish with scallion.",
    ],
  ),

  seed(
    "tuna_free_pasta_salad",
    "Chickpea pasta salad",
    6,
    20,
    ["lunch", "vegetarian", "fast", "no-cook"],
    ["pot"],
    [
      ri("pasta", 12, "oz"),
      ri("chickpeas", 2, "can"),
      ri("tomato", 1, "lb"),
      ri("zucchini", 1, "lb"),
      ri("olive_oil", 4, "tbsp"),
      ri("lemon", 2, "each"),
      ri("oregano", 2, "tsp"),
      ri("parmesan", 2, "oz", { optional: true }),
    ],
    [
      "Boil the pasta, rinse cool.",
      "Toss with chickpeas, diced tomato and raw zucchini ribbons.",
      "Dress with oil, lemon, oregano, salt and pepper.",
    ],
  ),

  seed(
    "potato_leek_chowder",
    "Potato, corn and cheddar chowder",
    6,
    40,
    ["dinner", "vegetarian", "soup", "batch"],
    ["pot"],
    [
      ri("potato", 2.5, "lb"),
      ri("frozen_corn", 16, "oz"),
      ri("onion", 1, "each"),
      ri("celery", 3, "stalk"),
      ri("milk", 3, "cup"),
      ri("butter", 3, "tbsp"),
      ri("flour", 3, "tbsp"),
      ri("veg_broth", 32, "floz"),
      ri("cheddar", 4, "oz"),
    ],
    [
      "Cook onion and celery in butter, stir in flour for one minute.",
      "Add broth and diced potato, simmer until tender.",
      "Add milk and corn, warm through, melt in the cheddar off heat.",
    ],
  ),

  seed(
    "chicken_tortilla_bake",
    "Chicken tortilla bake",
    6,
    50,
    ["dinner", "oven", "batch"],
    ["oven", "skillet"],
    [
      ri("chicken_breast", 1.5, "lb"),
      ri("corn_tortillas", 12, "each"),
      ri("black_beans", 2, "can"),
      ri("canned_tomatoes", 15, "oz"),
      ri("cheddar", 6, "oz"),
      ri("onion", 1, "each"),
      ri("cumin", 2, "tsp"),
      ri("chili_powder", 1, "tbsp"),
      ri("sour_cream", 4, "oz", { optional: true }),
    ],
    [
      "Poach and shred the chicken; mix with beans, tomatoes, onion and spices.",
      "Layer tortillas, filling and cheese twice in a baking dish.",
      "Bake 25 minutes at 375°F until bubbling.",
    ],
  ),

  seed(
    "lentil_bolognese",
    "Lentil bolognese",
    6,
    45,
    ["dinner", "vegetarian", "budget", "batch"],
    ["pot"],
    [
      ri("lentils", 1.5, "cup"),
      ri("pasta", 16, "oz"),
      ri("canned_tomatoes", 28, "oz"),
      ri("carrot", 0.5, "lb"),
      ri("celery", 3, "stalk"),
      ri("onion", 1, "each"),
      ri("garlic", 4, "clove"),
      ri("olive_oil", 3, "tbsp"),
      ri("oregano", 2, "tsp"),
    ],
    [
      "Finely dice the vegetables and soften them in oil.",
      "Add lentils, tomatoes and 3 cups water; simmer 30 minutes.",
      "Boil the pasta and toss with the sauce.",
    ],
  ),

  seed(
    "breakfast_for_dinner",
    "Oat pancakes with eggs and greens",
    4,
    30,
    ["dinner", "vegetarian", "fast", "budget"],
    ["skillet"],
    [
      ri("oats", 2, "cup"),
      ri("eggs", 6, "each"),
      ri("milk", 1.5, "cup"),
      ri("flour", 1, "cup"),
      ri("butter", 3, "tbsp"),
      ri("sugar", 2, "tbsp"),
      ri("spinach", 5, "oz"),
    ],
    [
      "Blend oats, flour, milk, two eggs and sugar into a batter; rest 10 minutes.",
      "Griddle the pancakes in butter.",
      "Fry the remaining eggs and wilt the spinach alongside.",
    ],
  ),
];

export const RECIPE_BY_ID: Record<string, Recipe> = Object.fromEntries(
  SEED_RECIPES.map((r) => [r.id, r]),
);
